---
title: "ESPN_Sports"
author: "Walt DeGrange"
date: "November 4, 2018"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE,message = FALSE)
```

```{r Libraries}
library(dplyr)
library(tidyr)
library(magrittr)
library(ggplot2)
library(purrr)
library(ggforce)
library(fpc)
library(cluster) 
library(mclust)
library(kableExtra)
library(formattable)
library(stargazer)
library(lares)
```

# Sports Analytics - Does it make a difference?

```{r Data Import, echo=FALSE}
TeamData <- read.csv("ESPNSportsAnalytics.csv")
colnames(TeamData)[1] <- "Sport"
TeamData %<>% mutate(PopulationMil = digits(Market/1000000,1))
TeamDataKM <- TeamData %>% select(ESPNRating,X2014HF,X2015HF,X2016HF,X2017HF,Market)

```

## Overall
```{r}
TeamData %<>% group_by(Team) %>% mutate(HowFar = sum(X2014HF,X2015HF,X2016HF,X2017HF)/4)

TeamData %>% group_by(Sport) %>% summarise(count = n(), MeanESPN = digits(mean(ESPNRating),1), StdESPN = digits(sd(ESPNRating),1)) %>% kable() %>% kable_styling(c("striped","condensed"), full_width = F) %>% column_spec(column = 1:2, color = "black")
```


## Local Teams

```{r Local Teams}

TeamData %>% group_by(Sport,Team,HowFar) %>% filter(City == "Phoenix") %>%  summarise(count = n(), ESPN = (ESPNRating)) %>% select(Team,ESPN,HowFar) %>% kable() %>% kable_styling(c("striped","condensed"), full_width = F) %>% column_spec(column = 1:2, color = "black")


```

_____

# Champions

## 2014

```{r}
TeamData %>% filter(X2014HF == "5") %>%  select(Sport,Team,City,ESPNRating,PopulationMil) %>%  arrange(Sport) %>% head(10) %>%  kable() %>% kable_styling(c("striped","condensed"), full_width = F) %>% column_spec(column = 1:2, color = "black")
```

## 2015

```{r}
TeamData %>% filter(X2015HF == "5") %>%  select(Sport,Team,City,ESPNRating,PopulationMil) %>%  arrange(Sport) %>% head(10) %>%  kable() %>% kable_styling(c("striped","condensed"), full_width = F) %>% column_spec(column = 1:2, color = "black")
```

## 2016

```{r}
TeamData %>% filter(X2016HF == "5") %>%  select(Sport,Team,City,ESPNRating,PopulationMil) %>%  arrange(Sport) %>% head(10) %>%  kable() %>% kable_styling(c("striped","condensed"), full_width = F) %>% column_spec(column = 1:2, color = "black")
```


## 2017

```{r}
TeamData %>% filter(X2017HF == "5") %>%  select(Sport,Team,City,ESPNRating,PopulationMil) %>%  arrange(Sport) %>% head(10) %>%  kable() %>% kable_styling(c("striped","condensed"), full_width = F) %>% column_spec(column = 1:2, color = "black")
```

_____

## Team list grouped by ESPN Ranking

```{r}

TeamData$PopulationMil <- digits(TeamData$PopulationMil,1)

TeamData %>% group_by(ESPNRating) %>% summarise(Count = n(), HowFar = digits(sum(X2014HF,X2015HF,X2016HF,X2017HF)/(4*n()),1), MeanPop = digits(mean(PopulationMil),1)) %>% kable() %>% kable_styling(c("striped","condensed"), full_width = F) %>% column_spec(column = 1:2, color = "black")
```


## Ten best ESPN Rating performers
```{r}
TeamData %>% select(Sport,Team,City,ESPNRating,PopulationMil,HowFar) %>% arrange(-HowFar) %>% head(10, ESPNRating)  %>% kable() %>% kable_styling(c("striped","condensed"), full_width = F) %>% column_spec(column = 1:2, color = "black")

```
\medskip

## Ten bottom ESPN Rating performers
```{r}

TeamData %>% select(Sport,Team,City,ESPNRating,PopulationMil,HowFar) %>%  arrange(-ESPNRating,HowFar) %>% head(10) %>%  kable() %>% kable_styling(c("striped","condensed"), full_width = F) %>% column_spec(column = 1:2, color = "black")
```
____

## Data Summary

```{r Market Summary,results='asis'}
TeamDataDF <- TeamData %>% select(c(ESPNRating,PopulationMil)) %>%  data.frame()
ESPNTable <- stargazer(TeamDataDF, type="html", align = TRUE, digits=1)
```


## Big to Small Market Teams
### Los Angeles
```{r Big to Small Market}

TeamData %>% group_by(Sport,Team,HowFar) %>% filter(City %in% c("Los Angeles","Anaheim")) %>%  summarise(count = n(), ESPN = (ESPNRating)) %>% select(Team,ESPN,HowFar) %>% kable() %>% kable_styling(c("striped","condensed"), full_width = F) %>% column_spec(column = 1:2, color = "black")


```
### New York
```{r}
TeamData %>% group_by(Sport,Team,HowFar) %>% filter(City %in% c("New York")) %>%  summarise(count = n(), ESPN = (ESPNRating)) %>% select(Team,ESPN,HowFar) %>% kable() %>% kable_styling(c("striped","condensed"), full_width = F) %>% column_spec(column = 1:2, color = "black")


```
### Green Bay
```{r}
TeamData %>% group_by(Sport,Team,HowFar) %>% filter(City %in% c("Green Bay")) %>%  summarise(count = n(), ESPN = (ESPNRating)) %>% select(Team,ESPN,HowFar) %>% kable() %>% kable_styling(c("striped","condensed"), full_width = F) %>% column_spec(column = 1:2, color = "black")
```

## Plot of ESPN vs How Far a team made it into the playoffs on average for the 4 years of data

```{r Plots}

TeamData %>% ggplot(aes(x=ESPNRating,y=HowFar)) +
  geom_point()+
  geom_smooth()


```

## K Means clustering

```{r KMeans Cluster}

TeamDataKM <- scale(TeamDataKM)

# Determine number of clusters
# wss <- (nrow(TeamDataKM)-1)*sum(apply(TeamDataKM,2,var))
# for (i in 2:15) wss[i] <- sum(kmeans(TeamDataKM,
#   	centers=i)$withinss)
# plot(1:15, wss, type="b", xlab="Number of Clusters",
#   ylab="Within groups sum of squares")

fit <- kmeans(TeamDataKM, 2)

TeamDataKM <- data.frame(TeamDataKM, fit$cluster)

TeamData <- data.frame(TeamData, fit$cluster)

rownames(TeamData) <- paste(TeamData$Sport,TeamData$Team,sep="")

clusplot(TeamData, fit$cluster, color=TRUE, shade=FALSE, 
  	labels=2, lines=0, cex.txt = .5,col.clus = c("red", "green"),col.txt = c("black", "black"))

TeamData %>% group_by(TeamData$fit.cluster) %>% summarise(count=n(),MeanX2014HF = digits(mean(X2014HF),1),MeanX2015HF = digits(mean(X2015HF),1),MeanX2016HF = digits(mean(X2016HF),1),MeanX2017HF = digits(mean(X2017HF),1),MeanPopulation = digits(mean(PopulationMil),1),MeanESPNRating = digits(mean(ESPNRating),1)) %>% kable() %>% kable_styling(c("striped","condensed"), full_width = F) %>% column_spec(column = 1:2, color = "black")
```

